import * as asset from "@canva/asset/test";
import * as design from "@canva/design/test";
import * as error from "@canva/error/test";
import * as intents from "@canva/intents/test";
import * as platform from "@canva/platform/test";
import * as user from "@canva/user/test";
asset.initTestEnvironment();
design.initTestEnvironment();
error.initTestEnvironment();
intents.initTestEnvironment();
platform.initTestEnvironment();
user.initTestEnvironment();
jest.mock("@canva/asset");
jest.mock("@canva/design");
jest.mock("@canva/intents");
jest.mock("@canva/platform");
jest.mock("@canva/user");
